"""empty message

Revision ID: 03198f1b1702
Revises: a4199e6db8b8
Create Date: 2021-11-03 15:15:01.464831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03198f1b1702'
down_revision = 'a4199e6db8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###
